spring:
  profiles.active: prod
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mercado_livre?useTimezone=true&serverTimezone=America/Sao_Paulo
    username: root
    password: ajudazupper
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    format-sql: true
    hibernate.ddl-auto: update

server.error.include-message: always

jwt:
  expiration: 14400000
  secret: rm'!@N=Ke!~p8VTA2ZRK~nMDQX5Uvm!m'D&]{@Vr?G;2?XhbC:Qa#9#eMLN\}x3?JR3.2zr~v)gYF^8\:8>:XfB:Ww75N/emt9Yj[bQMNCWwW\J?N,nvH.<2\.r~w]*e~vgak)X"v8H`MH/7"2E`,^k@n<vE-wD3g9JWPy;CrY*.Kd2_D])=><D?YhBaSua5hW%{2]_FVXzb9`8FH^b[X3jzVER&:jw2<=c38=>L/zBq`}C6tT*cCSVC^c]-L}&/
  internal_token: eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJNZXJjYWRvIExpdnJlIEFQSSIsInN1YiI6IjEiLCJpYXQiOjE2MTQ4NjcxNDd9.mzbrExaME3ugpmKnH8HHTxrejRNdEhRFSgjkAPSDNZI

